[package]
name = "node-cli"
version = "0.4.0"
authors = ["Liebi Technologies <bifrost@liebi.com>"]
description = "Bifrost Parachain Node"
build = "build.rs"
default-run = "bifrost-node"
edition = "2018"

[[bin]]
name = "bifrost-node"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.4" }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "14.2.0"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }
tracing = "0.1.10"
parking_lot = "0.10.0"

# primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-finality-tracker = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

# client dependencies
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-transaction-pool = {git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "sc-finality-grandpa" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-client-db = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
sc-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

# frame dependencies
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

# node-specific dependencies
node-runtime = { path = "../runtime" }
node-primitives = { path = "../primitives" }

# CLI-specific dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }
node-inspect = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }

# new added after removed local node-rpc, node-primitives
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = "substrate-browser-utils", git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }

# for initialize producer schedule
brml-bridge-eos = { path = "../../../brml/bridge-eos", default-features = false }
eos-chain = { git = "https://github.com/bifrost-finance/rust-eos" }

# brml rpc crates
brml-assets-rpc = { path = "../../../brml/assets/rpc" }
brml-convert-rpc = { path = "../../../brml/convert/rpc" }
bs58 = { version = "0.3.0", default-features = false, features = ["alloc"] }

[target.'cfg(target_arch="x86_64")'.dependencies]
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true, features = [ "wasmtime" ] }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false, features = [ "wasmtime" ] }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false, features = ["memory-tracker"] }

[dev-dependencies]
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", features = ["test-helpers"] }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
sc-service-test = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }
futures = "0.3.4"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.17"
serde_json = "1.0"
regex = "1"
platforms = "0.2.1"

[build-dependencies]
structopt = { version = "0.3.8", optional = true }
node-inspect = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }

[build-dependencies.sc-cli]
package = "sc-cli"
git = "https://github.com/paritytech/substrate"
branch = "rococo-branch"
optional = true

[features]
default = [ "cli" ]
browser = [
	"browser-utils",
	"wasm-bindgen",
	"wasm-bindgen-futures",
]
cli = [
	"sc-executor/wasmi-errno",
	"node-inspect",
	"sc-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
]
