[package]
name = "node-runtime"
version = "0.4.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
serde = { version = "1.0.106", optional = true }
static_assertions = "1.1.0"
hex-literal = { version = "0.2.1", optional = true }

# primitives
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-staking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", optional = true }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }

# frame dependencies
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false, optional = true }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-babe = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-democracy = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-finality-tracker = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-identity = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-offences = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-offences-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false, optional = true }
pallet-proxy = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-recovery = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", features = ["historical"], default-features = false }
pallet-session-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false, optional = true }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-society = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-treasury = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }
pallet-vesting = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false }

brml-assets = { path = "../../../brml/assets", default-features = false }
brml-assets-rpc-runtime-api = { path = "../../../brml/assets/rpc/runtime-api", default-features = false }
brml-bridge-eos = { path = "../../../brml/bridge-eos", default-features = false }
brml-convert = { path = "../../../brml/convert", default-features = false }
brml-convert-rpc-runtime-api = { path = "../../../brml/convert/rpc/runtime-api", default-features = false }
brml-oracle = { path = "../../../brml/oracle", default-features = false }
brml-proxy-validator = { path = "../../../brml/proxy-validator", default-features = false }
brml-swap = { path = "../../../brml/swap", default-features = false }
brml-voucher = { path = "../../../brml/voucher", default-features = false }
chainlink = { package = "pallet-chainlink", path = "../../../brml/chainlink", default-features = false }
node-primitives = { default-features = false, path = "../primitives" }

[build-dependencies]
wasm-builder-runner = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", package = "substrate-wasm-builder-runner" }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch" }

[features]
default = ["std"]
std = [
	"sp-authority-discovery/std",
	"pallet-authority-discovery/std",
	"pallet-authorship/std",
	"sp-consensus-babe/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"sp-block-builder/std",
	"codec/std",
	"pallet-collective/std",
	"pallet-democracy/std",
	"pallet-elections-phragmen/std",
	"frame-executive/std",
	"pallet-finality-tracker/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-indices/std",
	"sp-inherents/std",
	"pallet-membership/std",
	"pallet-multisig/std",
	"pallet-identity/std",
	"pallet-scheduler/std",
	"node-primitives/std",
	"sp-offchain/std",
	"pallet-offences/std",
	"pallet-proxy/std",
	"sp-core/std",
	"pallet-randomness-collective-flip/std",
	"sp-std/std",
	"serde",
	"pallet-session/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-staking/std",
	"sp-keyring",
	"sp-session/std",
	"pallet-sudo/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	"sp-transaction-pool/std",
	"pallet-utility/std",
	"sp-version/std",
	"pallet-society/std",
	"pallet-recovery/std",
	"pallet-vesting/std",
	"brml-assets/std",
	"brml-assets-rpc-runtime-api/std",
	"brml-bridge-eos/std",
	"brml-convert/std",
	"brml-convert-rpc-runtime-api/std",
	'brml-oracle/std',
	'brml-proxy-validator/std',
	"brml-swap/std",
	'brml-voucher/std',
	'chainlink/std',
]
